export interface Coordinates {
  latitude: number;
  longitude: number;
}

export interface User {
  id: string;
  username: string;
  avatar?: string;
  bio?: string; // Personal message/signature
}

export interface Capsule {
  id: string;
  content: string; // Text content or caption
  timestamp: number;
  coordinates: Coordinates;
  locationName?: string; // Human readable location
  aiAnalysis?: string; // Generated by Gemini
  isLocked: boolean; // True if user is too far away
  image?: string; // Base64 data URL
  video?: string; // Base64 data URL
  audio?: string; // Base64 data URL
  signalData?: string; // Serialized JSON of the sequencer grid
  userId: string; // Owner of the capsule
}

export interface SystemStatus {
  gps: 'searching' | 'locked' | 'denied' | 'error';
  network: 'online' | 'offline';
  scanner: 'idle' | 'scanning' | 'detecting';
}

export type ViewState = 'radar' | 'create' | 'view-capsule' | 'ar-view' | 'profile' | 'signal-composer';